
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ivan
 */
public class GameF_1 extends javax.swing.JFrame implements ActionListener {
  public static ArrayList<String>value=new ArrayList<>();
   
  /**
     * Creates new form GameF
     */
    public GameF_1() {
        value.add("1");
        value.add("2");
        value.add("5");
        value.add("10");
        value.add("25");
        value.add("50");
        value.add("75");
        value.add("100");
        value.add("200");
        value.add("300");
        value.add("400");
        value.add("500");
        value.add("750");
        value.add("1,000");
        value.add("5,000");
        value.add("10,000");
        value.add("25,000");
        value.add("50,000");
        value.add("75,000");
        value.add("100,000");
        value.add("200,000");
        value.add("300,000");
        value.add("400,000");
        value.add("500,000");
        value.add("750,000");
        value.add("1,000,000");
        
        initComponents();
        
        
        btn1.addActionListener(this);
        btn2.addActionListener(this);
        btn3.addActionListener(this);
        btn4.addActionListener(this);
        btn5.addActionListener(this);
        btn6.addActionListener(this);
        btn7.addActionListener(this);
        btn8.addActionListener(this);
        btn9.addActionListener(this);
        btn10.addActionListener(this);
        btn11.addActionListener(this);
        btn12.addActionListener(this);
        btn13.addActionListener(this);
        btn14.addActionListener(this);
        btn15.addActionListener(this);
        btn16.addActionListener(this);
        btn17.addActionListener(this);
        btn18.addActionListener(this);
        btn19.addActionListener(this);
        btn20.addActionListener(this);
        btn21.addActionListener(this);
        btn22.addActionListener(this);
        btn23.addActionListener(this);
        btn24.addActionListener(this);
        btn25.addActionListener(this);
        btn26.addActionListener(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn18 = new javax.swing.JButton();
        btn19 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn24 = new javax.swing.JButton();
        btn25 = new javax.swing.JButton();
        btn26 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cb1 = new javax.swing.JLabel();
        cb2 = new javax.swing.JLabel();
        cb3 = new javax.swing.JLabel();
        cb4 = new javax.swing.JLabel();
        cb5 = new javax.swing.JLabel();
        cb6 = new javax.swing.JLabel();
        cb7 = new javax.swing.JLabel();
        cb8 = new javax.swing.JLabel();
        cb9 = new javax.swing.JLabel();
        cb10 = new javax.swing.JLabel();
        cb11 = new javax.swing.JLabel();
        cb12 = new javax.swing.JLabel();
        cb13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cb14 = new javax.swing.JLabel();
        cb15 = new javax.swing.JLabel();
        cb16 = new javax.swing.JLabel();
        cb17 = new javax.swing.JLabel();
        cb18 = new javax.swing.JLabel();
        cb19 = new javax.swing.JLabel();
        cb20 = new javax.swing.JLabel();
        cb21 = new javax.swing.JLabel();
        cb22 = new javax.swing.JLabel();
        cb23 = new javax.swing.JLabel();
        cb24 = new javax.swing.JLabel();
        cb25 = new javax.swing.JLabel();
        cb26 = new javax.swing.JLabel();
        btn27 = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn1.setBackground(new java.awt.Color(51, 51, 51));
        btn1.setText("1");
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn1MouseEntered(evt);
            }
        });
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 92, -1, -1));

        btn2.setBackground(new java.awt.Color(51, 51, 51));
        btn2.setText("2");
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn2MouseEntered(evt);
            }
        });
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 92, -1, -1));

        btn3.setBackground(new java.awt.Color(51, 51, 51));
        btn3.setText("3");
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn3MouseEntered(evt);
            }
        });
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 92, -1, -1));

        btn4.setBackground(new java.awt.Color(51, 51, 51));
        btn4.setText("4");
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn4MouseEntered(evt);
            }
        });
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 92, -1, -1));

        btn5.setBackground(new java.awt.Color(51, 51, 51));
        btn5.setText("5");
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn5MouseEntered(evt);
            }
        });
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 140, -1, -1));

        btn6.setBackground(new java.awt.Color(51, 51, 51));
        btn6.setText("6");
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn6MouseEntered(evt);
            }
        });
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 140, -1, -1));

        btn7.setBackground(new java.awt.Color(51, 51, 51));
        btn7.setText("7");
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn7MouseEntered(evt);
            }
        });
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 140, -1, -1));

        btn8.setBackground(new java.awt.Color(51, 51, 51));
        btn8.setText("8");
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn8MouseEntered(evt);
            }
        });
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 140, -1, -1));

        btn9.setBackground(new java.awt.Color(51, 51, 51));
        btn9.setText("9");
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn9MouseEntered(evt);
            }
        });
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 174, -1, -1));

        btn10.setBackground(new java.awt.Color(51, 51, 51));
        btn10.setText("10");
        btn10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn10MouseEntered(evt);
            }
        });
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        getContentPane().add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 174, -1, -1));

        btn11.setBackground(new java.awt.Color(51, 51, 51));
        btn11.setText("11");
        btn11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn11MouseEntered(evt);
            }
        });
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        getContentPane().add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 174, -1, -1));

        btn12.setBackground(new java.awt.Color(51, 51, 51));
        btn12.setText("12");
        btn12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn12MouseEntered(evt);
            }
        });
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        getContentPane().add(btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 174, -1, -1));

        btn13.setBackground(new java.awt.Color(51, 51, 51));
        btn13.setText("13");
        btn13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn13MouseEntered(evt);
            }
        });
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });
        getContentPane().add(btn13, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 215, -1, -1));

        btn14.setBackground(new java.awt.Color(51, 51, 51));
        btn14.setText("14");
        btn14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn14MouseEntered(evt);
            }
        });
        btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14ActionPerformed(evt);
            }
        });
        getContentPane().add(btn14, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 215, -1, -1));

        btn15.setBackground(new java.awt.Color(51, 51, 51));
        btn15.setText("15");
        btn15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn15MouseEntered(evt);
            }
        });
        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });
        getContentPane().add(btn15, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 215, -1, -1));

        btn16.setBackground(new java.awt.Color(51, 51, 51));
        btn16.setText("16");
        btn16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn16MouseEntered(evt);
            }
        });
        btn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn16ActionPerformed(evt);
            }
        });
        getContentPane().add(btn16, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 215, -1, -1));

        btn17.setBackground(new java.awt.Color(51, 51, 51));
        btn17.setText("17");
        btn17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn17MouseEntered(evt);
            }
        });
        btn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn17ActionPerformed(evt);
            }
        });
        getContentPane().add(btn17, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 249, -1, -1));

        btn18.setBackground(new java.awt.Color(51, 51, 51));
        btn18.setText("18");
        btn18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn18MouseEntered(evt);
            }
        });
        btn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn18ActionPerformed(evt);
            }
        });
        getContentPane().add(btn18, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 249, -1, -1));

        btn19.setBackground(new java.awt.Color(51, 51, 51));
        btn19.setText("19");
        btn19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn19MouseEntered(evt);
            }
        });
        btn19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn19ActionPerformed(evt);
            }
        });
        getContentPane().add(btn19, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 249, -1, -1));

        btn20.setBackground(new java.awt.Color(51, 51, 51));
        btn20.setText("20");
        btn20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn20MouseEntered(evt);
            }
        });
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });
        getContentPane().add(btn20, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 249, -1, -1));

        btn21.setBackground(new java.awt.Color(51, 51, 51));
        btn21.setText("21");
        btn21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn21MouseEntered(evt);
            }
        });
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });
        getContentPane().add(btn21, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 290, -1, -1));

        btn22.setBackground(new java.awt.Color(51, 51, 51));
        btn22.setText("22");
        btn22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn22MouseEntered(evt);
            }
        });
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });
        getContentPane().add(btn22, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 290, -1, -1));

        btn23.setBackground(new java.awt.Color(51, 51, 51));
        btn23.setText("23");
        btn23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn23MouseEntered(evt);
            }
        });
        btn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn23ActionPerformed(evt);
            }
        });
        getContentPane().add(btn23, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 290, -1, -1));

        btn24.setBackground(new java.awt.Color(51, 51, 51));
        btn24.setText("24");
        btn24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn24MouseEntered(evt);
            }
        });
        btn24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn24ActionPerformed(evt);
            }
        });
        getContentPane().add(btn24, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 290, -1, -1));

        btn25.setBackground(new java.awt.Color(51, 51, 51));
        btn25.setText("25");
        btn25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn25MouseEntered(evt);
            }
        });
        btn25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn25ActionPerformed(evt);
            }
        });
        getContentPane().add(btn25, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 331, -1, -1));

        btn26.setBackground(new java.awt.Color(51, 51, 51));
        btn26.setText("26");
        btn26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn26MouseEntered(evt);
            }
        });
        btn26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn26ActionPerformed(evt);
            }
        });
        getContentPane().add(btn26, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 331, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        cb1.setForeground(new java.awt.Color(255, 255, 255));
        cb1.setText("$1");

        cb2.setForeground(new java.awt.Color(255, 255, 255));
        cb2.setText("$2");

        cb3.setForeground(new java.awt.Color(255, 255, 255));
        cb3.setText("$5");

        cb4.setForeground(new java.awt.Color(255, 255, 255));
        cb4.setText("$10");

        cb5.setForeground(new java.awt.Color(255, 255, 255));
        cb5.setText("$25");

        cb6.setForeground(new java.awt.Color(255, 255, 255));
        cb6.setText("$50");

        cb7.setForeground(new java.awt.Color(255, 255, 255));
        cb7.setText("$75");

        cb8.setForeground(new java.awt.Color(255, 255, 255));
        cb8.setText("$100");

        cb9.setForeground(new java.awt.Color(255, 255, 255));
        cb9.setText("$200");

        cb10.setForeground(new java.awt.Color(255, 255, 255));
        cb10.setText("$300");

        cb11.setForeground(new java.awt.Color(255, 255, 255));
        cb11.setText("$400");

        cb12.setForeground(new java.awt.Color(255, 255, 255));
        cb12.setText("$500");

        cb13.setForeground(new java.awt.Color(255, 255, 255));
        cb13.setText("$750");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cb13)
                    .addComponent(cb12)
                    .addComponent(cb11)
                    .addComponent(cb10)
                    .addComponent(cb9)
                    .addComponent(cb8)
                    .addComponent(cb7)
                    .addComponent(cb6)
                    .addComponent(cb5)
                    .addComponent(cb4)
                    .addComponent(cb3)
                    .addComponent(cb2)
                    .addComponent(cb1))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(cb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb13)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 400));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        cb14.setForeground(new java.awt.Color(255, 255, 255));
        cb14.setText("$1,000");

        cb15.setForeground(new java.awt.Color(255, 255, 255));
        cb15.setText("$5,000");

        cb16.setForeground(new java.awt.Color(255, 255, 255));
        cb16.setText("$10,000");

        cb17.setForeground(new java.awt.Color(255, 255, 255));
        cb17.setText("$25,000");

        cb18.setForeground(new java.awt.Color(255, 255, 255));
        cb18.setText("$50,000");

        cb19.setForeground(new java.awt.Color(255, 255, 255));
        cb19.setText("$75,000");

        cb20.setForeground(new java.awt.Color(255, 255, 255));
        cb20.setText("$100,000");

        cb21.setForeground(new java.awt.Color(255, 255, 255));
        cb21.setText("$200,000");

        cb22.setForeground(new java.awt.Color(255, 255, 255));
        cb22.setText("$300,000");

        cb23.setForeground(new java.awt.Color(255, 255, 255));
        cb23.setText("$400,000");

        cb24.setForeground(new java.awt.Color(255, 255, 255));
        cb24.setText("$500,000");

        cb25.setForeground(new java.awt.Color(255, 255, 255));
        cb25.setText("$750,000");

        cb26.setForeground(new java.awt.Color(255, 255, 255));
        cb26.setText("$1,000,000");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cb26)
                    .addComponent(cb25)
                    .addComponent(cb24)
                    .addComponent(cb23)
                    .addComponent(cb22)
                    .addComponent(cb21)
                    .addComponent(cb20)
                    .addComponent(cb19)
                    .addComponent(cb18)
                    .addComponent(cb17)
                    .addComponent(cb16)
                    .addComponent(cb15)
                    .addComponent(cb14))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(cb14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb26)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 16, -1, 400));
        getContentPane().add(btn27, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 373, 40, 30));

        lblMsg.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblMsg.setForeground(new java.awt.Color(255, 255, 255));
        lblMsg.setText("Escoja un maletin");
        getContentPane().add(lblMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgen/panelnew.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1MouseEntered

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2MouseEntered

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3MouseEntered

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn14ActionPerformed

    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn15ActionPerformed

    private void btn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn16ActionPerformed

    private void btn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn17ActionPerformed

    private void btn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn18ActionPerformed

    private void btn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn19ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn22ActionPerformed

    private void btn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn23ActionPerformed

    private void btn24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn24ActionPerformed

    private void btn25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn25ActionPerformed

    private void btn26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn26ActionPerformed

    private void btn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4MouseEntered

    private void btn5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5MouseEntered

    private void btn6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn6MouseEntered

    private void btn7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7MouseEntered

    private void btn8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8MouseEntered

    private void btn9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn9MouseEntered

    private void btn10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn10MouseEntered

    private void btn11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn11MouseEntered

    private void btn12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn12MouseEntered

    private void btn13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn13MouseEntered

    private void btn14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn14MouseEntered

    private void btn15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn15MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn15MouseEntered

    private void btn16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn16MouseEntered

    private void btn17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn17MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn17MouseEntered

    private void btn18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn18MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn18MouseEntered

    private void btn19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn19MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn19MouseEntered

    private void btn20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn20MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn20MouseEntered

    private void btn21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn21MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn21MouseEntered

    private void btn22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn22MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn22MouseEntered

    private void btn23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn23MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn23MouseEntered

    private void btn24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn24MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn24MouseEntered

    private void btn25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn25MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn25MouseEntered

    private void btn26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn26MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn26MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameF_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameF_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameF_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameF_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameF_1().setVisible(true);
            }
        });
    }
    public Icon setIcono(String a,JButton b){
        ImageIcon icon = new ImageIcon(getClass().getResource(a));
        int anc = b.getWidth();
        int alt = b.getHeight();
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(anc, alt, Image.SCALE_DEFAULT));
        return icono;
    }
  public static Integer i=0;
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn18;
    private javax.swing.JButton btn19;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn24;
    private javax.swing.JButton btn25;
    private javax.swing.JButton btn26;
    private javax.swing.JButton btn27;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JLabel cb1;
    private javax.swing.JLabel cb10;
    private javax.swing.JLabel cb11;
    private javax.swing.JLabel cb12;
    private javax.swing.JLabel cb13;
    private javax.swing.JLabel cb14;
    private javax.swing.JLabel cb15;
    private javax.swing.JLabel cb16;
    private javax.swing.JLabel cb17;
    private javax.swing.JLabel cb18;
    private javax.swing.JLabel cb19;
    private javax.swing.JLabel cb2;
    private javax.swing.JLabel cb20;
    private javax.swing.JLabel cb21;
    private javax.swing.JLabel cb22;
    private javax.swing.JLabel cb23;
    private javax.swing.JLabel cb24;
    private javax.swing.JLabel cb25;
    private javax.swing.JLabel cb26;
    private javax.swing.JLabel cb3;
    private javax.swing.JLabel cb4;
    private javax.swing.JLabel cb5;
    private javax.swing.JLabel cb6;
    private javax.swing.JLabel cb7;
    private javax.swing.JLabel cb8;
    private javax.swing.JLabel cb9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMsg;
    // End of variables declaration//GEN-END:variables
  public void actionPerformed(ActionEvent e) {
        if(e.getSource()==btn1){
            game(btn1,"1");
        }
        if(e.getSource()==btn2){
            game(btn2,"2");
        }
        if(e.getSource()==btn3){
            game(btn3,"3");
        }
        if(e.getSource()==btn4){
            game(btn4,"4");
        }
        if(e.getSource()==btn5){
            game(btn5,"5");
        }
        if(e.getSource()==btn6){
            game(btn6,"6");
        }
        if(e.getSource()==btn7){
            game(btn7,"7");
        }
        if(e.getSource()==btn8){
            game(btn8,"8");
        }
        if(e.getSource()==btn9){
            game(btn9,"9");
        }
        if(e.getSource()==btn10){
            game(btn10,"10");
        }
        if(e.getSource()==btn11){
            game(btn11,"11");
        }
        if(e.getSource()==btn12){
            game(btn12,"12");
        }
        if(e.getSource()==btn13){
            game(btn13,"13");
        }
        if(e.getSource()==btn14){
            game(btn14,"14");
        }
        if(e.getSource()==btn15){
            game(btn15,"15");
        }
        if(e.getSource()==btn16){
            game(btn16,"16");
        }
        if(e.getSource()==btn17){
            game(btn17,"17");
        }
        if(e.getSource()==btn18){
            game(btn18,"18");
        }
        if(e.getSource()==btn19){
            game(btn19,"19");
        }
        if(e.getSource()==btn20){
            game(btn20,"20");
        }
        if(e.getSource()==btn21){
            game(btn21,"21");
        }
        if(e.getSource()==btn22){
            game(btn22,"22");
        }
        if(e.getSource()==btn23){
            game(btn23,"23");
        }
        if(e.getSource()==btn24){
            game(btn24,"24");
        }
        if(e.getSource()==btn25){
            game(btn25,"25");
        }
        if(e.getSource()==btn26){
            game(btn26,"26");
        }
        
        
    }
    public void game(JButton a,String b){
        switch(i){
                case 0:jugar(a,b);
           i++;
                break;
                case 1:
                case 2:
                case 3:
                case 4:
                case 5:
                case 7:
                case 8:
                case 9:
                case 10:
                case 12:
                case 13:
                case 14:
                case 16:
                case 17:
                case 19:
                    int pos=((int) (Math.random() * value.size()));
                    apagar(value.get(pos));
                    JOptionPane.showMessageDialog(this, value.get(pos),"case", 0);
                    value.remove(pos);
                    a.setVisible(false); 
                    i++;
                break;
                case 6:
                case 11:
                case 15:
                case 18:
                case 20:
                case 21:
                case 22:
                case 23:
                    pos=((int) (Math.random() * value.size()));
                    apagar(value.get(pos));
                    JOptionPane.showMessageDialog(this, value.get(pos),"case", 0);
                    a.setVisible(false);
                    value.remove(pos);
                    Integer oferta=calcularoferta();
                    oferta=oferta/value.size()-1;
                    int respuesta=JOptionPane.showConfirmDialog(this, "La banca ofrece:"+oferta,"Oferta de la banca",JOptionPane.YES_NO_OPTION);
                    if(respuesta==0){
                        JOptionPane.showMessageDialog(this,"Felicidades Ganaste :$"+oferta ,"fin del juego", 0);
                        i=-1;
                        resetcase();
                    }
                    
                    i++;
                    break;
                case 24:
                    pos=((int) (Math.random() * value.size()));
                    JOptionPane.showMessageDialog(this, value.get(pos),"case", 0);
                    apagar(value.get(pos));
                    value.remove(pos);
                    a.setVisible(false);
                    oferta=calcularoferta();
                    oferta=oferta/value.size()-1;
                    respuesta=JOptionPane.showConfirmDialog(this, "La banca ofrece:"+oferta,"Oferta de la banca",JOptionPane.YES_NO_OPTION);
                    if(respuesta==0){
                        JOptionPane.showMessageDialog(this,"Felicidades Ganaste:$ "+oferta ,"fin del juego", 0);
                        i=0;
                        resetcase();
                    }i++;
                    respuesta=JOptionPane.showConfirmDialog(this, "¿Deseas quedarte tu maletin?","Utimo maletin",JOptionPane.YES_NO_OPTION);
                    if(respuesta==0){
                        JOptionPane.showMessageDialog(this,"Felicidades ganaste: $"+ value.get(0),"case", 0);
                        i=0;
                        resetcase();
                    }else{
                        JOptionPane.showMessageDialog(this,"Felicidades ganaste: $"+ value.get(1),"case", 0);
                        i=0;
                        resetcase();
                    }
                    break;
                case 25:i=0;
                    resetcase();
                    break;
            }
    
    }
     public void jugar (JButton a, String b){
        a.setVisible(false);
        String d="/Images/"+b+"a.png";
        System.out.println(d);
        btn27.setIcon(setIcono(d,btn27));
        lblMsg.setText("Open a case");
    }
    public void resetcase(){
        value.clear();
        value.add("1");
        value.add("2");
        value.add("5");
        value.add("10");
        value.add("25");
        value.add("50");
        value.add("75");
        value.add("100");
        value.add("200");
        value.add("300");
        value.add("400");
        value.add("500");
        value.add("750");
        value.add("1,000");
        value.add("5,000");
        value.add("10,000");
        value.add("25,000");
        value.add("50,000");
        value.add("75,000");
        value.add("100,000");
        value.add("200,000");
        value.add("300,000");
        value.add("400,000");
        value.add("500,000");
        value.add("750,000");
        value.add("1,000,000");
        btn1.setVisible(true);
        btn2.setVisible(true);
        btn3.setVisible(true);
        btn4.setVisible(true);
        btn5.setVisible(true);
        btn6.setVisible(true);
        btn7.setVisible(true);
        btn8.setVisible(true);
        btn9.setVisible(true);
        btn10.setVisible(true);
        btn11.setVisible(true);
        btn12.setVisible(true);
        btn13.setVisible(true);
        btn14.setVisible(true);
        btn15.setVisible(true);
        btn16.setVisible(true);
        btn17.setVisible(true);
        btn18.setVisible(true);
        btn19.setVisible(true);
        btn20.setVisible(true);
        btn21.setVisible(true);
        btn22.setVisible(true);
        btn23.setVisible(true);
        btn24.setVisible(true);
        btn25.setVisible(true);
        btn26.setVisible(true);
        lblMsg.setText("Selecccione");
               /* cb1.clean();
                cb2.clean();
                cb3.clean();
                cb4.clean();
                cb5.clean();
                cb6.clean();
                cb7.clean();
                cb8.clean();
                cb9.clean();
                cb10.clean();
                cb11.clean();
                cb12.clean();
                cb13.clean2();
                cb14.clean2();
                cb15.clean2();
                cb16.clean2();
                cb17.clean2();
                cb18.clean2();
                cb19.clean2();
                cb20.clean2();
                cb21.clean2();
                cb22.clean2();
                cb23.clean2();
                cb24.clean2();
                cb25.clean2();
                cb26.clean2();*/
        }
    public void apagar(String a){
        System.out.println(a);
        switch (a){
            case "1":
                cb1.addPropertyChangeListener(background);
                break;   
            case "10":
                cb2.doClick();
                break;
            case "100":
                cb3.doClick();
                break;
            case "1,000":
                cb4.doClick();
                break;
            case "10,000":
                cb5.doClick();
                break;
            case "100,000":
                cb6.doClick();
                break;
            case "1,000,000":
                cb6.doClick();
                break;
            case "2":
               cb8.doClick();
                break;
            case "200":
                cb9.doClick();
                break;
            case "200,000":
                cb10.doClick();
                break;    
            case "25":
                cb11.doClick();
                break;
            case "25,000":
                cb12.doClick();
                break;
            case "300":
                cb13.doClick();
                break;
            case "300,000":
                cb14.doClick();
                break;
            case "400":
                cb15.doClick();
                break;
            case "400,000":
                cb16.doClick();
                break;  
            case "5":
                cb17.doClick();
                break;
            case "50":
                cb18.doClick();
                break;
            case "500":
                cb19.doClick();
                break;
             case "5,000":
                cb20.doClick();
                break;  
            case "50,000":
                cb21.doClick();
                break;
            case "500,000":
                cb22.doClick();
                break;
            case "75":
                cb23.doClick();
                break;
            case "750":
                cb24.doClick();
                break;
            case "75,000":
                cb25.doClick();
                break;  
            case "750,000":
                cb26.doClick();
                break;
        }
    }
        public Integer calcularoferta(){
        int i=0;
        Integer a=0;
        while(i<value.size()){
            switch (value.get(i)){
            case "1":
                a+=1;
                break;   
            case "10":
                a+=10;
                break;
            case "100":
                a+=100;
                break;
            case "1,000":
                a+=1000;
                break;
            case "10,000":
                a+=10000;
                break;
            case "100,000":
                a+=100000;
                break;
            case "1,000,000":
                a+=1000000;
                break;
            case "2":
                a+=2;
                break;
            case "200":
                a+=200;
                break;
            case "200,000":
                a+=200000;
                break;    
            case "25":
                a+=25;
                break;
            case "25,000":
                a+=25000;
                break;
            case "300":
                a+=300;
                break;
            case "300,000":
                a+=300000;
                break;
            case "400":
                a+=400;
                break;
            case "400,000":
                a+=400000;
                break;  
            case "5":
                a+=5;
                break;
            case "50":
                a+=50;
                break;
            case "500":
                a+=500;
                break;
             case "5,000":
                a+=5000;
                break;  
            case "50,000":
                a+=50000;
                break;
            case "500,000":
                a+=500000;
                break;
            case "75":
                a+=75;
                break;
            case "750":
                a+=750;
                break;
            case "75,000":
                a+=75000;
                break;  
            case "750,000":
                a+=750000;
                break;
        }
            i++;
        }
            System.out.println("///"+a);
        return a;
    }
}